import rgbDataURL from './lib/rgbDataURL';

export default [
  {
    id: '1',
    title: 'Flipkart Offices',
    featured_media: {
      src: '/projects/glyfada/6.png',
      blurDataURL: rgbDataURL(84, 87, 89),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '2',
    title: 'Lil',
    featured_media: {
      src: '/projects/stefanos/1.png',
      blurDataURL: rgbDataURL(165, 151, 141),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '3',
    title: 'Beyoncé',
    featured_media: {
      src: '/projects/glyfada/6.png',
      blurDataURL: rgbDataURL(84, 87, 89),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '4',
    title: 'Lil',
    featured_media: {
      src: '/projects/stefanos/1.png',
      blurDataURL: rgbDataURL(165, 151, 141),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '5',
    title: 'LeBron',
    featured_media: {
      src: '/projects/glyfada/6.png',
      blurDataURL: rgbDataURL(84, 87, 89),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '6',
    title: 'Lil',
    featured_media: {
      src: '/projects/stefanos/1.png',
      blurDataURL: rgbDataURL(165, 151, 141),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '7',
    title: 'Beyoncé',
    featured_media: {
      src: '/projects/glyfada/6.png',
      blurDataURL: rgbDataURL(84, 87, 89),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
  {
    id: '8',
    title: 'Lil',
    featured_media: {
      src: '/projects/stefanos/1.png',
      blurDataURL: rgbDataURL(165, 151, 141),
    },
    size: 965,
    date: 2020,
    content: [
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
      '/projects/glyfada/6.png',
    ],
  },
];
