import rgbDataURL from './lib/rgbDataURL';

export default [
  {
    id: '1',
    title: 'Residential building Glyfada',
    featured_media: {
      src: '/projects/glyfada/img1.png',
      blurDataURL: rgbDataURL(84, 87, 89),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/glyfada/img2.png', col: 4 },
      img2: { src: '/projects/glyfada/img3.png', col: 7 },
      img3: { src: '/projects/glyfada/img4.png', col: 7 },
    },
  },
  {
    id: '2',
    title: 'Sea Restaurant Syros',
    featured_media: {
      src: '/projects/syros_restaurant/img1.png',
      blurDataURL: rgbDataURL(170, 163, 162),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/syros_restaurant/img2.png', col: 4 },
      img2: { src: '/projects/syros_restaurant/img3.png', col: 7 },
      img3: { src: '/projects/syros_restaurant/img4.png', col: 7 },
      img4: { src: '/projects/syros_restaurant/img5.png', col: 12 },
    },
  },
  {
    id: '3',
    title: 'Whealth Store Ermoupoly',
    featured_media: {
      src: '/projects/whealth_store/img1.png',
      blurDataURL: rgbDataURL(94, 82, 68),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/whealth_store/img2.png', col: 4 },
      img2: { src: '/projects/whealth_store/img3.png', col: 7 },
      img3: { src: '/projects/whealth_store/img4.png', col: 7 },
      img4: { src: '/projects/whealth_store/img5.png', col: 12 },
      img5: { src: '/projects/whealth_store/img6.png', col: 4 },
      img6: { src: '/projects/whealth_store/img7.png', col: 7 },
      img7: { src: '/projects/whealth_store/img8.png', col: 7 },
    },
    immersive:
      'https://api2.enscape3d.com/v3/view/ccb34841-dd37-4217-a126-5c583a24aa16',
  },
  {
    id: '4',
    title: 'Villa Syros',
    featured_media: {
      src: '/projects/villa_syros/img1.png',
      blurDataURL: rgbDataURL(165, 151, 142),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/villa_syros/img2.png', col: 4 },
      img2: { src: '/projects/villa_syros/img3.png', col: 7 },
      img3: { src: '/projects/villa_syros/img4.png', col: 7 },
      img4: { src: '/projects/villa_syros/img5.png', col: 12 },
      img5: { src: '/projects/villa_syros/img6.png', col: 4 },
      img6: { src: '/projects/villa_syros/img7.png', col: 7 },
      img7: { src: '/projects/villa_syros/img8.png', col: 7 },
      img8: { src: '/projects/villa_syros/img9.png', col: 4 },
    },
  },
  {
    id: '5',
    title: 'Renovation house Scotland',
    featured_media: {
      src: '/projects/scotland/featured_img.jpg',
      blurDataURL: rgbDataURL(188, 184, 185),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/scotland/img1.jpg', col: 4 },
      img2: { src: '/projects/scotland/img2.jpg', col: 7 },
      img3: { src: '/projects/scotland/img3.jpg', col: 7 },
      img4: { src: '/projects/scotland/img4.jpg', col: 12 },
      // img5: { src: '/projects/scotland/img5.jpg', col: 4 },
      img6: { src: '/projects/scotland/img6.jpg', col: 7 },
      img7: { src: '/projects/scotland/img7.jpg', col: 4 },
      img10: { src: '/projects/scotland/img10.jpg', col: 4 },
      img8: { src: '/projects/scotland/img8.jpg', col: 7 },
      img9: { src: '/projects/scotland/img9.jpg', col: 7 },
      img11: { src: '/projects/scotland/img11.jpg', col: 4 },
      img12: { src: '/projects/scotland/img12.jpg', col: 4 },
      img13: { src: '/projects/scotland/img13.jpg', col: 7 },
    },
  },
  {
    id: '6',
    title: 'Resort Hotel Dubai',
    featured_media: {
      src: '/projects/resort_dubai/featured_img.png',
      blurDataURL: rgbDataURL(165, 149, 134),
    },
    size: 965,
    date: 2020,
    content: {
      img1: { src: '/projects/resort_dubai/img1.png', col: 4 },
      img2: { src: '/projects/resort_dubai/img2.png', col: 7 },
      img3: { src: '/projects/resort_dubai/img3.png', col: 7 },
      img4: { src: '/projects/resort_dubai/img4.png', col: 4 },
      img5: { src: '/projects/resort_dubai/img5.png', col: 4 },
      img6: { src: '/projects/resort_dubai/img6.png', col: 7 },
      img7: { src: '/projects/resort_dubai/img7.png', col: 7 },
      img8: { src: '/projects/resort_dubai/img8.png', col: 12 },
      img9: { src: '/projects/resort_dubai/img9.png', col: 4 },
      img10: { src: '/projects/resort_dubai/img10.png', col: 7 },
      img11: { src: '/projects/resort_dubai/img11.png', col: 7 },
      img12: { src: '/projects/resort_dubai/img12.png', col: 12 },
      img13: { src: '/projects/resort_dubai/img13.png', col: 7 },
    },
  },
];
